name: MapPainting
main: net.aegistudio.mpp.MapPainting
version: 1.2-beta
author: aegistudio
commands:
  mpp:
    description: Command service provided by map painting.
    usage: /mpp <subcommand> [<parameters>]
    permission: mpp.command
    permission-message: You don't have permission to do that!
permissions:
  mpp.paint:
    description: Grants player to paint on canvas he owns.
    default: true
  mpp.interact:
    description: Grants player to interact with a canvas.
    default: true
  mpp.command:
    description: Grants player to issue map painting command.
    default: true
  mpp.create.*:
    description: Grants player to create any canvas.
    children:
      mpp.create.normal: true
  mpp.create.normal:
    description: Grants player to create canvas of type "normal".
    default: true
  mpp.chown:
    description: Grants player to change ownership of canvas he owns.
    default: true
  mpp.chmod:
    description: Grants player to add or remove painters of his canvas.
    default: true
  mpp.destroy:
    description: Grants player to destroy the canvas he owns.
    default: true
  mpp.pigment:
    description: Grants player to obtain a pigment by RGB color directly.
    default: op
  mpp.undo:
    description: Grants player to perform undo on his canvas.
    default: true
  mpp.redo:
    description: Grants player to perform redo on his canvas.
    default: true
  mpp.manager:
    description: Grants player to manage canvas.
    default: op
